name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Verify Modules
      run: make verify-modules

    - name: Build
      run: make local
      
    - name: Test
      env:
        VELERO_PLUGIN_AEOS_TEST_CONFIG: ${{ secrets.VELERO_PLUGIN_AEOS_TEST_CONFIG }}
        AZURE_STORAGE_ACCOUNT_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_ACCESS_KEY }}
        AZURE_STORAGE_ACCOUNT_ENCRYPTION_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_ENCRYPTION_KEY }}
        AZURE_STORAGE_ACCOUNT_ENCRYPTION_HASH: ${{ secrets.AZURE_STORAGE_ACCOUNT_ENCRYPTION_HASH }}
      run: make test
